### ISSUE TITLE
Moreziqi

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-lite#217]
We have [new design work](https://xd.adobe.com/view/69bd464d-d17c-472d-9ddf-dd5a1a2ec972-3cee/grid) for Wuziqi from Kekya

CSS and HTML can bee pulled from the [Adobe Preview](https://xd.adobe.com/view/69bd464d-d17c-472d-9ddf-dd5a1a2ec972-3cee/grid)

The menu design shoudl be left out of this work and considered for general inclusion. (This would involve checking how things look for all games that use the menu in all formats.

Asstes are attached in a comment below.

**Comment by arpee** [comment]
[Wuziqi.zip](https://github.com/SaitoTech/saito-lite/files/7240413/Wuziqi.zip)

**Comment by f8daniel** [comment]
I'm not really sure what I can do with this. The design is very pretty, but the format is functionally equivalent to Photoshop, i.e. layers of overlapping photo elements, where the "css" is just specifying the (x,y) coordinates of the assets. 
Happy to update the tiles, but I really don't know how to organize 18 different sized images for each game piece.

**Comment by arpee** [comment]
Agree, think we need to organise for Kekya to give us the board without lines (so that we can manage these) and the tile images, background etc.

Then the rest would be manually creating CSS to 'recreate' the design in HTML/CSS - you up for that?

**Comment by arpee** [comment]
Have just seen what you did in [your latest wuziqi commit](https://github.com/SaitoTech/saito-lite/pull/209/files/83b6d89737a123dd269c15125718fe75d32acd96..5a09a0d507b19d17da29df14ac249537625cfc0c) and that is a huge part of what i was thinking.

I took the liberty to do some CSS hackery and move the crud under the tiles... 

You up for adding player boxes that look like what kekya put together?

(We could move that to a later release.

**Comment by f8daniel** [comment]
Ok, I see you added that to the wuziqi branch under my fork. It's going to be fun resolving all the merge conflicts when this finally goes to deploy. 
Yeah, I think I can borrow the basic logic of player boxes from the blackjack module to display player name, color, score, and status messages. Shouldn't take me too long

**Comment by trevelyan** [comment]
Hey -- I actually have a suggestion on how we handle this if you haven't
made too much headway Dan:

/lib/saito/ui/game-playerbox

It would be nice to have a generic UI component to handle creating and
displaying the playerboxes.

Right now those boxes are hardcoded in every game and it makes the UI and
CSS hard to update. When Kekya has come along with a "redesign" I've punted
every time because it would mean hacking up games one-by-one. If we had a
component we could just add them programmatically to each game.

Our general trend with the Web3 gaming stuff has been carving out
game-generic functions into these components (overlay, HUD, cardbox) so
that the games themselves can mix-and-match the pieces they want. I doubt
that we would be keen on backporting this stuff to poker or blackjack
anytime soon, but it would make it MUCH easier for adding new card games,
which we are almost certainly going to want to do once the Mixin stuff is
in. And it might even make sense to do it with Poker and Blackjack once we
have UI components that work and make interface easier.

Would also be great way to get up-to-speed with how our other UI elements
work. Either for ripping them down or replacing them.

**Comment by f8daniel** [comment]
I made a note to that effect on my kanban not too long ago, specifically thinking about game.css and /lib/saito/ui/game-menu. I've just been hesitant to both impose my will on the system and make changes in places that could ripple out to other modules and could potentially break (UI) things. 

I have been hacking up games one-by-one, but I haven't encountered all of the generic game components yet. So, I'm not sure how much a playerbox is going to overlap/interfere with HUD for example. However, I think I could give it a try and integrate it into the games I am familiar with (and where it would be useful).
