### ISSUE TITLE
Game gets stuck if the player doesn't have cards to discard upon reaching Bear Has Landed

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#73]
If one of the players gets to 'Bear Has Landed' on the space race but has no cards to discard, the game will break.

Made a gif:
![BHL](https://user-images.githubusercontent.com/54612963/75942431-bb49b100-5e68-11ea-8184-1b5d6bcb5fb9.gif)

No matter what you choose, it won't advance further.

**Comment by trevelyan** [comment]
thx, good one to catch.

**Comment by Rammko** [comment]
I have been testing this for the last couple of days and after fulfilling the conditions well over 5 times I believe that you are experiencing a different bug. What is happening here is what we're calling the UI lock from clicking on cards or display or players and then clicking on status. The UI gets locked and you cant choose anything, its not tied to Bear/Eagle has landed. This can happen anywhere where you are given a choice with text that you need to click on the UI. for example, once you click on a card and you get the option to play event, play for ops or space race, if you click on cards or display or players and then back to status you're stuck and have to refresh. Not sure if you had done anything else prior to recording this, but that may be the issue, if you had refreshed then you would have surely been able to click on discard without issue.


[Recording #7.zip](https://github.com/SaitoTech/saito-lite/files/4308352/Recording.7.zip)

Uploading a video because I don't know how to make a gif, it shows the exact issue you had and how it happened after a refresh and then after another refresh it shows that you can in fact hit discard without it breaking the game even if you have no cards in hand

**Comment by trevelyan** [comment]
The problem has been fixed, but perhaps not updated live to server yet.

Closing is fine. Issue will go away soon.
